//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Tentakel
// 
//      It contains classes defined from the contents of the resource file:
//        C:\Development\Tentakel\Tentakel.Extensions.Logging\dev-André\Tentakel.Extensions.Logging\SR.srt.resx
// 
//      Generated: Tuesday, May 11, 2021 7:38 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Tentakel.Extensions.Logging
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SRKeys.Culture;
            }
            set
            {
                SRKeys.Culture = value;
            }
        }
        
        public static string PossibleDeadlockDetected
        {
            get
            {
                return SRKeys.GetString(SRKeys.PossibleDeadlockDetected);
            }
        }
        
        public static string BackgroundWorkerHasBeenDisposed
        {
            get
            {
                return SRKeys.GetString(SRKeys.BackgroundWorkerHasBeenDisposed);
            }
        }
        
        public static string BackgroundWorkerIsNotRunning
        {
            get
            {
                return SRKeys.GetString(SRKeys.BackgroundWorkerIsNotRunning);
            }
        }
    }
    
    internal class SRKeys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Tentakel.Extensions.Logging.SR.srt", typeof(Tentakel.Extensions.Logging.SR).Assembly);
        
        static System.Globalization.CultureInfo _culture = null;
        
        public const string PossibleDeadlockDetected = "PossibleDeadlockDetected";
        
        public const string BackgroundWorkerHasBeenDisposed = "BackgroundWorkerHasBeenDisposed";
        
        public const string BackgroundWorkerIsNotRunning = "BackgroundWorkerIsNotRunning";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return _culture;
            }
            set
            {
                _culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, _culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, _culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}

