//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        D:\dev\git\oleander\extensions\Oleander.Extensions.Logging\src\SR.srt.resx
// 
//      Generated: Monday, March 18, 2024 9:54 AM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Oleander.Extensions.Logging
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SRKeys.Culture;
            }
            set
            {
                SRKeys.Culture = value;
            }
        }
        
        public static string PossibleDeadlockDetected
        {
            get
            {
                return SRKeys.GetString(SRKeys.PossibleDeadlockDetected);
            }
        }
        
        public static string BackgroundWorkerHasBeenDisposed
        {
            get
            {
                return SRKeys.GetString(SRKeys.BackgroundWorkerHasBeenDisposed);
            }
        }
        
        public static string BackgroundWorkerIsNotRunning
        {
            get
            {
                return SRKeys.GetString(SRKeys.BackgroundWorkerIsNotRunning);
            }
        }
    }
    
    internal partial class SRKeys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Oleander.Extensions.Logging.SR.srt", typeof(Oleander.Extensions.Logging.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string PossibleDeadlockDetected = "PossibleDeadlockDetected";
        
        public const string BackgroundWorkerHasBeenDisposed = "BackgroundWorkerHasBeenDisposed";
        
        public const string BackgroundWorkerIsNotRunning = "BackgroundWorkerIsNotRunning";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
