<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyVersion>1.5.0.2</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <SourceRevisionId>3a5c0f9f31ea5dc546a2ff4801418550ff9b922e</SourceRevisionId>
    <VersionSuffix></VersionSuffix>
    <Version Condition="'$(VersionSuffix)' != ''">$(AssemblyVersion)-$(VersionSuffix)</Version>
    <Version Condition="'$(VersionSuffix)' == ''">$(AssemblyVersion)</Version>
    <InformationalVersion>$(AssemblyVersion)</InformationalVersion>
    <Description>Oleander DependencyInjection Extensions</Description>
    <PackageTags>Oleander; Extensions; DependencyInjection; C#</PackageTags>
  </PropertyGroup>

  <Import Project="..\..\Common\targets\common.targets" />
  <Import Project="..\..\Common\targets\generatePackage.targets" />

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="Oleander.Assembly.Versioning.BuildTask" Version="1.5.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Oleander.Extensions.Configuration\src\Oleander.Extensions.Configuration.csproj" />
  </ItemGroup>

</Project>
