<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyVersion>2.0.1.1</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <SourceRevisionId>3a5c0f9f31ea5dc546a2ff4801418550ff9b922e</SourceRevisionId>
    <VersionSuffix></VersionSuffix>
    <Version Condition="'$(VersionSuffix)' != ''">$(AssemblyVersion)-$(VersionSuffix)</Version>
    <Version Condition="'$(VersionSuffix)' == ''">$(AssemblyVersion)</Version>
    <InformationalVersion>$(AssemblyVersion)</InformationalVersion>
    <Description>Oleander Configuration extensions</Description>
    <PackageTags>Oleander; Extensions; Configuration; C#</PackageTags>
  </PropertyGroup>

  <Import Project="..\..\Common\targets\common.targets" />
  <Import Project="..\..\Common\targets\generatePackage.targets" />

  <ItemGroup>
    <Compile Include="..\..\Common\src\NullableAttributes.cs" Link="Common\NullableAttributes.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="Oleander.Assembly.Versioning.BuildTask" Version="1.5.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>
</Project>
