name: 'deployNugetPackages'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    - release
    
  workflow_dispatch:

env:
  VERSION_SUFFIX: ${{ github.base_ref || github.ref_name }}
  PACKOUTDIR: ${{ github.workspace }}\packoutput
                    
jobs:
  deploy:
    name: 'Deploy packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
     - name: 'echo github.event_name'
       shell: bash
       run: echo ${{ github.event_name }}

     - name: 'echo VERSION_SUFFIX'
       shell: bash
       run: echo ${{ env.VERSION_SUFFIX }}

     - name: 'Set VERSION_SUFFIX: dev'
       if: env.VERSION_SUFFIX == 'main'
       shell: bash
       run: echo "VERSION_SUFFIX=dev" >> $GITHUB_ENV

     - name: 'echo VERSION_SUFFIX 2'
       shell: bash
       run: echo ${{ env.VERSION_SUFFIX }}

     - name: 'Set VERSION_SUFFIX: string.Empty'
       # if: ${{ startsWith(env.VERSION_SUFFIX, 'release') }}
       if: env.VERSION_SUFFIX == 'release'
       shell: bash
       run: echo "VERSION_SUFFIX=" >> $GITHUB_ENV

     - name: 'echo VERSION_SUFFIX 3'
       shell: bash
       run: echo ${{ env.VERSION_SUFFIX }}

     - name: 'Checkout'
       uses: actions/checkout@v4
     
     - name: 'Install dotnet2'
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '2.0.x'

     - name: 'Install dotnet8'
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '8.0.x'

     - name: 'Add GitHub to Nuget source'
       uses: 'Andre-Loetzsch/actions/addGitHubToNugetSource@v1'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}


     - name: 'Build and test extensions.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@v2 
       with:
         solution: '${{ github.workspace }}\extensions.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         packoutdir: ${{ env.PACKOUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'delete Oleander.Extensions.Configuration-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Configuration'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Configuration.Json-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Configuration.Json'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.DependencyInjection-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.DependencyInjection'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging.Abstractions-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging.Abstractions'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging.Console-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging.Console'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging.File-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging.File'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging.TextFormatters-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging.TextFormatters'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging.TextFormatters.Abstractions-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging.TextFormatters.Abstractions'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Logging.ZipFile-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Logging.ZipFile'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"
         
     - name: 'delete Oleander.Extensions.Hosting.Abstractions-dev old packages'
       if: env.VERSION_SUFFIX == 'dev'
       uses: actions/delete-package-versions@v5
       with:
         package-name: 'Oleander.Extensions.Hosting.Abstractions'
         package-type: 'nuget'
         min-versions-to-keep: 5
         delete-only-pre-release-versions: "true"

     - name: 'push nuget packages'
       if: matrix.os == 'windows-latest' && github.event_name != 'pull_request'
       uses: Andre-Loetzsch/actions/pushNugetPackages@v1
       with:
         outdir: ${{ env.PACKOUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'push nuget packages to nuget gallery'
       if: matrix.os == 'windows-latest' && github.event_name != 'pull_request' && env.VERSION_SUFFIX == ''
       uses: Andre-Loetzsch/actions/pushNugetPackagesToNugetOrg@v1
       with:
         packagedir: ${{ env.PACKOUTDIR }}
         nuget_apikey: ${{ secrets.NUGETORG_ACCESS_TOKEN }}
