name: 'deployNugetPackages'
# description: "deploy nuget packages to github"

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ nuget ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION_SUFFIX: 'DEV'
  OUTDIR: ${{ github.workspace }}\output
                    
jobs:
  deploy:
    name: 'Deploy packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    
     - name: 'Checkout'
       uses: actions/checkout@v3
     - name: 'Install dotnet'
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: '6.0.x'

     - name: 'Add GitHub to Nuget source'
       uses: 'Andre-Loetzsch/actions/addGitHubToNugetSource@main'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.Configuration.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@main
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.Configuration\Tentakel.Extensions.Configuration.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.Configuration.Json.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@main
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.Configuration.Json\Tentakel.Extensions.Configuration.Json.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.DependencyInjection.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@main
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.DependencyInjection\Tentakel.Extensions.DependencyInjection.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
     
       if: matrix.os == 'windows-latest'
     - uses: Andre-Loetzsch/actions/pushNugetPackages@main
       with:
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
