name: 'deployNugetPackages'

on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
    branches:
    - main
    - 'release/**'

  workflow_dispatch:

env:
  VERSION_SUFFIX: 'DEV'
  OUTDIR: ${{ github.workspace }}\output
                    
jobs:
  deploy:
    name: 'Deploy packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
    
     - name: 'Set VERSION_SUFFIX: string.Empty'
       if: ${{ !startsWith(github.ref_name, 'release/v') }}
       run: echo "" >> $VERSION_SUFFIX

     - name: 'Set VERSION_SUFFIX: alpha'
       if: ${{ !startsWith(github.ref_name, 'release/alpha') }}
       run: echo "alpha" >> $VERSION_SUFFIX

     - name: 'Set VERSION_SUFFIX: beta'
       if: ${{ !startsWith(github.ref_name, 'release/beta') }}
       run: echo "beta" >> $VERSION_SUFFIX

     - name: 'Checkout'
       uses: actions/checkout@v3
     - name: 'Install dotnet'
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: '6.0.x'

     - name: 'Add GitHub to Nuget source'
       uses: 'Andre-Loetzsch/actions/addGitHubToNugetSource@main'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.Configuration.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@main
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.Configuration\Tentakel.Extensions.Configuration.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.Configuration.Json.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@main
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.Configuration.Json\Tentakel.Extensions.Configuration.Json.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.DependencyInjection.sln'
       uses: Andre-Loetzsch/actions/buildAndTestSolution@main
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.DependencyInjection\Tentakel.Extensions.DependencyInjection.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
         
     - name: 'push nuget packages'
       if: matrix.os == 'windows-latest'
       uses: Andre-Loetzsch/actions/pushNugetPackages@main
       with:
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
