name: 'deployNugetPackages'
# description: "deploy nuget packages to github"

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ nuget ]
  # pull_request:
  #   branches: [ nuget ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION_SUFFIX: 'DEV'
  OUTDIR: ${{ github.workspace }}\output
                    
jobs:
  deploy:
    name: 'Deploy packages'
    runs-on: 'windows-latest'
    steps:
    
     - name: 'Checkout'
       uses: actions/checkout@v3
     - name: 'Install dotnet'
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: '6.0.x'

     - name: 'Add GitHub to Nuget source'
       uses: 'Andre-Loetzsch/actions/addGitHubToNugetSource@testworkflow'
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Build and test Tentakel.Extensions.Configuration.sln'
       uses: Andre-Loetzsch/actions/bildAndTestSolution@testworkflow
       with:
         solution: '${{ github.workspace }}\Tentakel.Extensions.Configuration\Tentakel.Extensions.Configuration.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - uses: Andre-Loetzsch/actions/bildAndTestSolution@testworkflow
       with:
         solution: '${{ github.workspace }}\nugetTest\NuGetConsoleApp\NuGetConsoleApp.sln'
         version-suffix: ${{ env.VERSION_SUFFIX }}
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}

     - uses: Andre-Loetzsch/actions/pushNugetPackages@testworkflow
       with:
         outdir: ${{ env.OUTDIR }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
